SELECT
    CASE WHEN B.GRADE < 8 THEN NULL
    ELSE A.NAME END AS NAME,
    B.GRADE,
    A.MARKS
FROM STUDENTS A
INNER JOIN GRADES B
ON A.MARKS BETWEEN B.MIN_MARK AND B.MAX_MARK
ORDER BY
    B.GRADE DESC, NAME, A.MARKS